name: Release JS SDK
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    uses: globalid/.github/.github/workflows/npm-publish.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
